import { Platform } from "react-native";

// প্রিমিয়াম টিল (আপনার HTML design)
const tealPrimary = "#1a5e63";
const tealSecondary = "#2d936c";
const tealAccent = "#f9a826";

// মডার্ন ব্লু
const bluePrimary = "#0066cc";
const blueSecondary = "#0099ff";
const blueAccent = "#ff6b35";

// এলিগ্যান্ট পার্পল
const purplePrimary = "#7c3aed";
const purpleSecondary = "#a78bfa";
const purpleAccent = "#f59e0b";

// ফ্রেশ গ্রীন
const greenPrimary = "#059669";
const greenSecondary = "#10b981";
const greenAccent = "#f97316";

// সানসেট অরেঞ্জ
const orangePrimary = "#ea580c";
const orangeSecondary = "#fb923c";
const orangeAccent = "#06b6d4";

export type ThemeName =
  | "teal"
  | "blue"
  | "purple"
  | "green"
  | "orange"
  | "bn"
  | "en"
  | "ur"
  | "hi"
  | "ar"
  | "tr"
  | "ms"
  | "id"
  | "pa"
  | "fa";

export const Colors = {
  // প্রিমিয়াম টিল থিম (HTML design)
  teal: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: tealPrimary,
      link: tealPrimary,
      primary: tealPrimary,
      primaryLight: tealSecondary,
      primaryDark: "#0f3a3f",
      secondary: tealSecondary,
      secondaryLight: "#4aaf8a",
      secondaryDark: "#1a5d45",
      accent: tealAccent,
      success: "#4CAF50",
      warning: tealAccent,
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f9f9f9",
      backgroundTertiary: "#eeeeee",
      border: "#e0e0e0",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: tealAccent,
      link: tealSecondary,
      primary: tealSecondary,
      primaryLight: "#4aaf8a",
      primaryDark: tealPrimary,
      secondary: tealAccent,
      secondaryLight: "#ffc049",
      secondaryDark: "#f0991e",
      accent: tealAccent,
      success: "#66BB6A",
      warning: tealAccent,
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#242424",
      backgroundSecondary: "#1e1e1e",
      backgroundTertiary: "#333333",
      border: "#404040",
    },
  },

  // মডার্ন ব্লু থিম
  blue: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: bluePrimary,
      link: bluePrimary,
      primary: bluePrimary,
      primaryLight: blueSecondary,
      primaryDark: "#003d99",
      secondary: blueSecondary,
      secondaryLight: "#33adff",
      secondaryDark: "#0073e6",
      accent: blueAccent,
      success: "#4CAF50",
      warning: blueAccent,
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f0f4ff",
      backgroundTertiary: "#e8ecff",
      border: "#d0doff",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: blueAccent,
      link: blueSecondary,
      primary: blueSecondary,
      primaryLight: "#66b3ff",
      primaryDark: bluePrimary,
      secondary: blueAccent,
      secondaryLight: "#ff8c66",
      secondaryDark: "#ff5722",
      accent: blueAccent,
      success: "#66BB6A",
      warning: blueAccent,
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#0a1f3d",
      backgroundSecondary: "#132847",
      backgroundTertiary: "#1a3a52",
      border: "#2a4a62",
    },
  },

  // এলিগ্যান্ট পার্পল থিম
  purple: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: purplePrimary,
      link: purplePrimary,
      primary: purplePrimary,
      primaryLight: purpleSecondary,
      primaryDark: "#5b21b6",
      secondary: purpleSecondary,
      secondaryLight: "#c4b5fd",
      secondaryDark: "#8b5cf6",
      accent: purpleAccent,
      success: "#4CAF50",
      warning: purpleAccent,
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f3f0ff",
      backgroundTertiary: "#ede9fe",
      border: "#ddd6fe",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: purpleAccent,
      link: purpleSecondary,
      primary: purpleSecondary,
      primaryLight: "#d8b4fe",
      primaryDark: purplePrimary,
      secondary: purpleAccent,
      secondaryLight: "#fbbf24",
      secondaryDark: "#f59e0b",
      accent: purpleAccent,
      success: "#66BB6A",
      warning: purpleAccent,
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#2d1b4e",
      backgroundSecondary: "#3d2463",
      backgroundTertiary: "#4d337a",
      border: "#6d4a8f",
    },
  },

  // ফ্রেশ গ্রীন থিম
  green: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: greenPrimary,
      link: greenPrimary,
      primary: greenPrimary,
      primaryLight: greenSecondary,
      primaryDark: "#047857",
      secondary: greenSecondary,
      secondaryLight: "#6ee7b7",
      secondaryDark: "#059669",
      accent: greenAccent,
      success: "#4CAF50",
      warning: greenAccent,
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f0fdf4",
      backgroundTertiary: "#dcfce7",
      border: "#bbf7d0",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: greenAccent,
      link: greenSecondary,
      primary: greenSecondary,
      primaryLight: "#86efac",
      primaryDark: greenPrimary,
      secondary: greenAccent,
      secondaryLight: "#fed7aa",
      secondaryDark: "#fb923c",
      accent: greenAccent,
      success: "#66BB6A",
      warning: greenAccent,
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#0f3f2f",
      backgroundSecondary: "#1a5a47",
      backgroundTertiary: "#25755f",
      border: "#309076",
    },
  },

  // সানসেট অরেঞ্জ থিম
  orange: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: orangePrimary,
      link: orangePrimary,
      primary: orangePrimary,
      primaryLight: orangeSecondary,
      primaryDark: "#c2410c",
      secondary: orangeSecondary,
      secondaryLight: "#fed7aa",
      secondaryDark: "#f97316",
      accent: orangeAccent,
      success: "#4CAF50",
      warning: orangeAccent,
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#fef3c7",
      backgroundTertiary: "#fed7aa",
      border: "#fecaca",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: orangeAccent,
      link: orangeSecondary,
      primary: orangeSecondary,
      primaryLight: "#ffa94d",
      primaryDark: orangePrimary,
      secondary: orangeAccent,
      secondaryLight: "#67e8f9",
      secondaryDark: "#06b6d4",
      accent: orangeAccent,
      success: "#66BB6A",
      warning: orangeAccent,
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#3f2515",
      backgroundSecondary: "#5a3a1f",
      backgroundTertiary: "#754f2a",
      border: "#9a6a35",
    },
  },

  // ভাষা-ভিত্তিক পেস্টেল থিম (ফ্ল্যাগ রঙ)
  // বাংলা - বাংলাদেশ (সবুজ)
  bn: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#428271",
      link: "#428271",
      primary: "#428271",
      primaryLight: "#5a9e88",
      primaryDark: "#2d5a56",
      secondary: "#4aaf8a",
      secondaryLight: "#7ec9b3",
      secondaryDark: "#268f6d",
      accent: "#f9a826",
      success: "#4CAF50",
      warning: "#f9a826",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f0f5f3",
      backgroundTertiary: "#e6f1ed",
      border: "#d6e8e1",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#4aaf8a",
      link: "#5a9e88",
      primary: "#4aaf8a",
      primaryLight: "#7ec9b3",
      primaryDark: "#428271",
      secondary: "#f9a826",
      secondaryLight: "#fbc55f",
      secondaryDark: "#f0931e",
      accent: "#f9a826",
      success: "#66BB6A",
      warning: "#f9a826",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#1e3a35",
      backgroundSecondary: "#284a42",
      backgroundTertiary: "#325a4f",
      border: "#3d6a5c",
    },
  },

  // ইংরেজি - আমেরিকা (নীল)
  en: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#24284f",
      link: "#24284f",
      primary: "#24284f",
      primaryLight: "#4a5080",
      primaryDark: "#1a1e38",
      secondary: "#4a5080",
      secondaryLight: "#6f75a3",
      secondaryDark: "#24284f",
      accent: "#FF6B9D",
      success: "#4CAF50",
      warning: "#FF6B9D",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f0f2f8",
      backgroundTertiary: "#e8ebf3",
      border: "#dce2ed",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#4a5080",
      link: "#4a5080",
      primary: "#4a5080",
      primaryLight: "#6f75a3",
      primaryDark: "#24284f",
      secondary: "#FF6B9D",
      secondaryLight: "#ff9fbf",
      secondaryDark: "#ff4a7b",
      accent: "#FF6B9D",
      success: "#66BB6A",
      warning: "#FF6B9D",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#1f2335",
      backgroundSecondary: "#2a2f42",
      backgroundTertiary: "#353d53",
      border: "#45505e",
    },
  },

  // উর্দু - পাকিস্তান (সবুজ)
  ur: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#5A8B6F",
      link: "#5A8B6F",
      primary: "#5A8B6F",
      primaryLight: "#7aaa8f",
      primaryDark: "#3d6450",
      secondary: "#7aaa8f",
      secondaryLight: "#9fc2b0",
      secondaryDark: "#5a8b6f",
      accent: "#FFA500",
      success: "#4CAF50",
      warning: "#FFA500",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f1f5f2",
      backgroundTertiary: "#e8f0eb",
      border: "#dce6df",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#7aaa8f",
      link: "#7aaa8f",
      primary: "#7aaa8f",
      primaryLight: "#9fc2b0",
      primaryDark: "#5A8B6F",
      secondary: "#FFA500",
      secondaryLight: "#ffc247",
      secondaryDark: "#ff8c00",
      accent: "#FFA500",
      success: "#66BB6A",
      warning: "#FFA500",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#1f3a32",
      backgroundSecondary: "#2d5041",
      backgroundTertiary: "#3a6650",
      border: "#477c5f",
    },
  },

  // হিন্দি - ভারত (কমলা)
  hi: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#FFD699",
      link: "#FFD699",
      primary: "#FFD699",
      primaryLight: "#ffe0b3",
      primaryDark: "#ffb84d",
      secondary: "#ffe0b3",
      secondaryLight: "#fff0d9",
      secondaryDark: "#ffc266",
      accent: "#FF8C42",
      success: "#4CAF50",
      warning: "#FF8C42",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#fef8f1",
      backgroundTertiary: "#fef1e6",
      border: "#fce5d3",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#ffe0b3",
      link: "#ffe0b3",
      primary: "#ffe0b3",
      primaryLight: "#fff0d9",
      primaryDark: "#FFD699",
      secondary: "#FF8C42",
      secondaryLight: "#ffb380",
      secondaryDark: "#ff6600",
      accent: "#FF8C42",
      success: "#66BB6A",
      warning: "#FF8C42",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#3d2820",
      backgroundSecondary: "#5a3d2a",
      backgroundTertiary: "#775238",
      border: "#946546",
    },
  },

  // আরবি - সৌদি আরব (সবুজ)
  ar: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#7FA88B",
      link: "#7FA88B",
      primary: "#7FA88B",
      primaryLight: "#9fbfa8",
      primaryDark: "#5f886d",
      secondary: "#9fbfa8",
      secondaryLight: "#bfd9cc",
      secondaryDark: "#7fa88b",
      accent: "#4CAF50",
      success: "#4CAF50",
      warning: "#4CAF50",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f2f5f3",
      backgroundTertiary: "#e9f1ed",
      border: "#dde7e1",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#9fbfa8",
      link: "#9fbfa8",
      primary: "#9fbfa8",
      primaryLight: "#bfd9cc",
      primaryDark: "#7FA88B",
      secondary: "#4CAF50",
      secondaryLight: "#81c784",
      secondaryDark: "#2e7d32",
      accent: "#4CAF50",
      success: "#66BB6A",
      warning: "#4CAF50",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#1f3a30",
      backgroundSecondary: "#2d5541",
      backgroundTertiary: "#3a7052",
      border: "#478b63",
    },
  },

  // তুর্কি - তুরস্ক (গোলাপি)
  tr: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#E68998",
      link: "#E68998",
      primary: "#E68998",
      primaryLight: "#eda6b0",
      primaryDark: "#d9617a",
      secondary: "#eda6b0",
      secondaryLight: "#f5c4d0",
      secondaryDark: "#e68998",
      accent: "#FF69B4",
      success: "#4CAF50",
      warning: "#FF69B4",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#fff0f5",
      backgroundTertiary: "#ffe6ed",
      border: "#ffd4e5",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#eda6b0",
      link: "#eda6b0",
      primary: "#eda6b0",
      primaryLight: "#f5c4d0",
      primaryDark: "#E68998",
      secondary: "#FF69B4",
      secondaryLight: "#ff94d0",
      secondaryDark: "#ff1493",
      accent: "#FF69B4",
      success: "#66BB6A",
      warning: "#FF69B4",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#3d1f2a",
      backgroundSecondary: "#57293a",
      backgroundTertiary: "#71334a",
      border: "#8b3d5a",
    },
  },

  // মালয় - মালয়েশিয়া (নীল)
  ms: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#7FA8F0",
      link: "#7FA8F0",
      primary: "#7FA8F0",
      primaryLight: "#a3c0f7",
      primaryDark: "#5f88e0",
      secondary: "#a3c0f7",
      secondaryLight: "#c4d9fd",
      secondaryDark: "#7fa8f0",
      accent: "#3498db",
      success: "#4CAF50",
      warning: "#3498db",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f1f6fd",
      backgroundTertiary: "#e8f1fb",
      border: "#d9e8f9",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#a3c0f7",
      link: "#a3c0f7",
      primary: "#a3c0f7",
      primaryLight: "#c4d9fd",
      primaryDark: "#7FA8F0",
      secondary: "#3498db",
      secondaryLight: "#66b8ff",
      secondaryDark: "#0078d7",
      accent: "#3498db",
      success: "#66BB6A",
      warning: "#3498db",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#1a2f50",
      backgroundSecondary: "#254368",
      backgroundTertiary: "#305880",
      border: "#3a6d98",
    },
  },

  // ইন্দোনেশিয়া - ইন্দোনেশিয়া (প্রবাল)
  id: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#FF9999",
      link: "#FF9999",
      primary: "#FF9999",
      primaryLight: "#ffb3b3",
      primaryDark: "#ff6666",
      secondary: "#ffb3b3",
      secondaryLight: "#ffd4d4",
      secondaryDark: "#ff7f7f",
      accent: "#FF6B6B",
      success: "#4CAF50",
      warning: "#FF6B6B",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#fff5f5",
      backgroundTertiary: "#ffebeb",
      border: "#ffd9d9",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#ffb3b3",
      link: "#ffb3b3",
      primary: "#ffb3b3",
      primaryLight: "#ffd4d4",
      primaryDark: "#FF9999",
      secondary: "#FF6B6B",
      secondaryLight: "#ff9999",
      secondaryDark: "#ff3333",
      accent: "#FF6B6B",
      success: "#66BB6A",
      warning: "#FF6B6B",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#3d1f1f",
      backgroundSecondary: "#5a2f2f",
      backgroundTertiary: "#773f3f",
      border: "#944f4f",
    },
  },

  // পাঞ্জাবি - পাকিস্তান/ভারত (সোনালি)
  pa: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#FFD699",
      link: "#FFD699",
      primary: "#FFD699",
      primaryLight: "#ffe0b3",
      primaryDark: "#ffb84d",
      secondary: "#ffe0b3",
      secondaryLight: "#fff0d9",
      secondaryDark: "#ffc266",
      accent: "#DAA520",
      success: "#4CAF50",
      warning: "#DAA520",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#fffef1",
      backgroundTertiary: "#fffce6",
      border: "#fff9d9",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#ffe0b3",
      link: "#ffe0b3",
      primary: "#ffe0b3",
      primaryLight: "#fff0d9",
      primaryDark: "#FFD699",
      secondary: "#DAA520",
      secondaryLight: "#f0c846",
      secondaryDark: "#cc8800",
      accent: "#DAA520",
      success: "#66BB6A",
      warning: "#DAA520",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#3d3520",
      backgroundSecondary: "#5a4d2e",
      backgroundTertiary: "#77653c",
      border: "#947d4a",
    },
  },

  // ফারসি - ইরান (গোলাপি)
  fa: {
    light: {
      text: "#1a1a1a",
      textSecondary: "#666666",
      buttonText: "#FFFFFF",
      tabIconDefault: "#999999",
      tabIconSelected: "#8FCC9F",
      link: "#8FCC9F",
      primary: "#8FCC9F",
      primaryLight: "#a8dab3",
      primaryDark: "#6fae85",
      secondary: "#a8dab3",
      secondaryLight: "#c6e8ce",
      secondaryDark: "#8fcc9f",
      accent: "#FF7F7F",
      success: "#4CAF50",
      warning: "#FF7F7F",
      error: "#f44336",
      backgroundRoot: "#f5f5f5",
      backgroundDefault: "#ffffff",
      backgroundSecondary: "#f3f8f5",
      backgroundTertiary: "#ecf4f0",
      border: "#deedea",
    },
    dark: {
      text: "#ffffff",
      textSecondary: "#b0b0b0",
      buttonText: "#FFFFFF",
      tabIconDefault: "#808080",
      tabIconSelected: "#a8dab3",
      link: "#a8dab3",
      primary: "#a8dab3",
      primaryLight: "#c6e8ce",
      primaryDark: "#8FCC9F",
      secondary: "#FF7F7F",
      secondaryLight: "#ffb3b3",
      secondaryDark: "#ff4444",
      accent: "#FF7F7F",
      success: "#66BB6A",
      warning: "#FF7F7F",
      error: "#ef5350",
      backgroundRoot: "#1a1a1a",
      backgroundDefault: "#1f3a2f",
      backgroundSecondary: "#2d5541",
      backgroundTertiary: "#3a7052",
      border: "#477c63",
    },
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  inputHeight: 48,
  buttonHeight: 52,
};

export const BorderRadius = {
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 32,
  "3xl": 40,
  full: 9999,
};

export const Typography = {
  display: {
    fontSize: 32,
    fontWeight: "700" as const,
  },
  h1: {
    fontSize: 24,
    fontWeight: "700" as const,
  },
  h2: {
    fontSize: 20,
    fontWeight: "600" as const,
  },
  h3: {
    fontSize: 18,
    fontWeight: "600" as const,
  },
  body: {
    fontSize: 16,
    fontWeight: "400" as const,
  },
  bodySmall: {
    fontSize: 14,
    fontWeight: "400" as const,
  },
  caption: {
    fontSize: 12,
    fontWeight: "400" as const,
  },
  arabicLarge: {
    fontSize: 28,
    fontWeight: "400" as const,
  },
  small: {
    fontSize: 14,
    fontWeight: "400" as const,
  },
  link: {
    fontSize: 16,
    fontWeight: "400" as const,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "Georgia",
    mono: "Courier New",
  },
  android: {
    sans: "system-ui",
    serif: "serif",
    mono: "monospace",
  },
  web: {
    sans: "system-ui",
    serif: "Georgia",
    mono: "monospace",
  },
});

export const Shadows = {
  sm: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    elevation: 1,
  },
  md: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  lg: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
  },
};
